language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo test --all
  - cargo test --all --no-default-features
  - if [ "$TARGET" = x86_64-unknown-linux-gnu ] && [ "$TRAVIS_RUST_VERSION" = stable ]; then
      rustup component add rustfmt;
      rustfmt -vV;
      cargo fmt --all -- --check;
    fi