[package]
name = "mdbook-plantuml"
version = "0.3.0"
authors = ["Sytse Reitsma <mdbook-plantuml@sreitsma.nl>"]
description = "A preprocessor for mdbook which will convert plantuml code blocks into inline SVG diagrams"
license = "MIT"
documentation = "https://docs.rs/mdbook-plantuml"
repository = "https://github.com/sytsereitsma/mdbook-plantuml"
readme = "README.md"
keywords = ["mdbook", "plantuml", "markdown", "commonmark"]
exclude = [
    "tests/e2etest",
]

[[bin]]
name = "mdbook-plantuml"
path = "src/bin/mdbook-plantuml.rs"
doc = false

[dependencies]
mdbook = "0.3.1"
serde = "1.0.92"
serde_json = "1.0.39"
log = "0.4.6"
env_logger = "0.6.1"
failure = "0.1.5"
serde_derive = "1.0.92"
failure_derive = "0.1.5"
pulldown-cmark = "0.5.2"
pulldown-cmark-to-cmark = "1.2.2"
clap = "2.33.0"
uuid = { version = "0.7.4", features = ["v4"] }
log4rs = "0.8.3"
reqwest = "0.9.20"
deflate = "0.8.0"

[dev-dependencies]
pretty_assertions = "0.6.1"
simulacrum = "0.3.1"
tempfile = "3.0.8"
