[package]
name = "mdbook-plantuml"
version = "0.5.0"
authors = ["Sytse Reitsma <mdbook-plantuml@sreitsma.nl>"]
description = "A preprocessor for mdbook which will convert plantuml code blocks into inline SVG diagrams"
license = "MIT"
documentation = "https://docs.rs/mdbook-plantuml"
repository = "https://github.com/sytsereitsma/mdbook-plantuml"
readme = "README.md"
keywords = ["mdbook", "plantuml", "markdown", "commonmark"]
exclude = [
    "tests/e2etest",
]

[[bin]]
name = "mdbook-plantuml"
path = "src/bin/mdbook-plantuml.rs"
doc = false

[features]
# no features by default
default = []

[dependencies]
mdbook = "0.3.4"
serde = "1.0.102"
serde_json = "1.0.41"
log = "0.4.8"
env_logger = "0.7.1"
failure = "0.1.6"
serde_derive = "1.0.102"
failure_derive = "0.1.6"
clap = "2.33.0"
uuid = { version = "0.8.1", features = ["v4"] }
log4rs = "0.8.3"
reqwest = {version = "0.9.22"}
deflate = {version = "0.8.2"}
sha1 = { version = "0.6.0", features = ["std"] }

[dev-dependencies]
pretty_assertions = "0.6.1"
simulacrum = "0.3.1"
tempfile = "3.1.0"
