[package]
name = "mdbook-plantuml"
version = "0.0.1"
authors = ["Sytse Reitsma <mdbook-plantuml@sreitsma.nl>"]
description = "A backend for `mdbook` which will add rendered PlantUML diagrams to your book."
license = "MIT"
documentation = "https://docs.rs/mdbook-plantuml"
repository = "https://github.com/sytsereitsma/mdbook-plantuml"
readme = "README.md"

[[bin]]
name = "mdbook-plantuml"
path = "src/bin/mdbook-plantuml.rs"
doc = false

[dependencies]
mdbook = { version = "0.2.3", default-features = false }
serde = "1.0.92"
serde_json = "1.0.39"
structopt = "0.2.16"
log = "0.4.6"
env_logger = "0.6.1"
failure = "0.1.5"
serde_derive = "1.0.92"
simple-error = "0.2.0"
glob = "0.3.0"

[dev-dependencies]
pretty_assertions = "0.6.1"
toml = "0.5.1"
